site_name: MkDocs DANS
site_description: A Material Design theme for MkDocs customised for DANS
site_url: https://Dans-labs.github.io/mkdocs-dans/
site_author: Martin Donath, customised by Dirk Roorda

repo_name: Dans-labs/mkdocs-dans
repo_url: https://github.com/Dans-labs/mkdocs-dans

theme:
  name: dans
  logo: 'images/formats.png'
  favicon: 'images/formats.png'
  development: true
  development_label: under development
  production_link: https://dans.knaw.nl/en
  client:
    name: Data Archiving and Networked Services (DANS)
    url: 'https://dans.knaw.nl/en'
    logo: assets/images/DANS.gif

  feature:
    tabs: false

  disclaimer: true

strict: false

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Dans-labs
      repo: mkdocs-dans
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  # - markdownextradata
  - search
  - minify:
      minify_html: true

# Page tree
nav:
  - DANS theme: index.md
  - Extensions:
    - Admonition: extensions/admonition.md
    - CodeHilite: extensions/codehilite.md
    - Footnotes: extensions/footnotes.md
    - Metadata: extensions/metadata.md
    - Permalinks: extensions/permalinks.md
    - PyMdown: extensions/pymdown.md
  - Specimen: specimen.md
  - Customization: customization.md
  - Compliance with GDPR: compliance.md
  - Release notes: release-notes.md
  - Author's notes: authors-notes.md
  - License: license.md

extra:
  dans: https://www.dans.knaw.nl
  markdown: https://daringfireball.net/projects/markdown/syntax
  mkdocs: https://www.mkdocs.org
